apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend
  namespace: devops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
    spec:
      containers:
        - name: backend
          image: YOUR_DOCKERHUB_USERNAME/devops-backend:IMAGE_TAG_PLACEHOLDER
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/employees/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: devops-backend
  namespace: devops-demo
spec:
  selector:
    app: devops-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
